kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarr-animes
  labels:
    app: sonarr-animes
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: sonarr-animes
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
        sidecar.opentelemetry.io/inject: "true"
      labels:
        app: sonarr-animes
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - nardine
      containers:
      - name: sonarr-animes
        image: ghcr.io/hotio/sonarr:latest
        ports:
        - name: sonarr-animes
          containerPort: 8989
        envFrom:
        - secretRef:
            name: sonarr-animes-secrets
        livenessProbe:
          httpGet:
            path: /
            port: 8989
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8989
          initialDelaySeconds: 10
          periodSeconds: 15
        volumeMounts:
        - name: sonarr-animes
          mountPath: /config
        - name: animes
          mountPath: /data/videos/animes-series
        - name: p2p
          mountPath: /data/torrent/complete/animes-tv
        - name: usenet
          mountPath: /data/usenet/complete/animes-tv
    #    - name: betarr-script
    #      mountPath: /etc/cont-init.d/99-betarr-setup.sh
    #      subPath: install-dependencies.sh
      volumes:
      - name: sonarr-animes
        hostPath:
          path: /k8s/sonarr-animes
          type: Directory
      - name: animes
        hostPath:
          path: /data/videos/animes-series
          type: Directory
      - name: p2p
        hostPath:
          path: /data/torrent/complete/animes-tv
          type: Directory
      - name: usenet
        hostPath:
          path: /data/usenet/complete/animes-tv
          type: Directory
   #   - name: betarr-script
   #     configMap:
   #       name: betarr
   #       defaultMode: 0755
