---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mongodb-secrets
  namespace: databases
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgCQNviyVjaT1t7AjnZvkpx2tOaFanUhGtTVMdYediU6xnByPYRuf8VWmzcaz5w0HBU8tN/GU3eFj0WgOo3huhywuQFlkGB5DVsf6GFLghtO7AjpS8xGuscUeuflQ8A4Znn3CWOtUMxYtgYVH47qD1MJ1pUXMcS/WuEV+cKkKpgMlFVUG3nvBX7appWGElwnoFzAw0V2Lash9ryAS80kwt9kCBIEUi1fovoXEccfjVV8mjsQZ0WAgMJ0odRceLxGwQVhNmUEOvChi7KU5hdmXmTj7khcjCLhvS+qvdyVOnQ4YHN9gjYgfg/7pojM0QuScCjRSjdNs2bpLxDx+n9adO82UV0YmlJsk74vYILLhVkAo7IVJt7qBk+ZFTgb924XKzBvVYNmwB/dpaoDR8k4G0P6Kk4fdjBlgskeqiqd4fP1hfSzKQ9fi59qRlQNOI1rzUSCt/IIXKClPGcN9aqglmTAqS3Q6P/asB9oYQw4p+LEjLsRmV6OhjvZDTSOP6R31BZ3EWgtlFH/FZvfz7vuHXtDdGxJVugRuvi7xjcHB0HMyfXtD1DRS4AxL3Hi5CCxS4KwTWtp16rjWf+ViEbNscrO97O/rCLt3QmITxqNEhdzLmCs1vHgV/fJH0G+oQ2QebLaDa9C1mJm17VJwuX+TuxdqHpLTjuiGyMXQU6qcDqBrOFC7FxOiupuLE0hL4vMWL6XSQw5s6JxmcS+AJOFn7mbKf4UJjSGI3WTb7nsHT/KLQ==
    MONGO_INITDB_ROOT_USERNAME: AgBK8d+XFRq/ZEit84zBzQBNdlZrRdv+qtwLUSHEEnuL/uqrQ9621VLTDZhbq+RbxyRhBAd+Rq5lm2NsRi7GrCPi+B6ys2RKsGOxJMz+wJe5jaj0+75xUT7SvX+DtUw6LSOncKf/X3YEsbD1x1ilXX+J2/1M1+qu+fRPWuB3yH0TiJIawYPfXxvVwXLbHTGtrVO+j0nYy2z9Iwc7d/6hGdUhGfPkfPkVUN64s7wYaMGHd6lWJhpjNkc1LhUicB4WfTtSNf8nEGIsglJsqOKiPhTmdM5knHMf5YS9O+eLXFFFdaEOTFsIRr5ITNIxfBlrJqEchVAdCZzjmso4EdvNJ1ENtVo/ljXrzET5wtMdjgh+tcVI/Opl+SWbuG5oGUndpO+ZQGvliGwFKKbwn1wGeZ6obC2bHsEII5U15qa+Wy/ZSaVoJPbxcXRmasWY/AHl1Fhhq69X2Ot+8wLhPsn2d7SLQvjO+480bAWjmc/hP9orsHGSSElgUxr812S365ZBsxDOH8vizIeDXys+tasdhDUuBe0hLYo0lWdA8e6FPg7pzXLmPHsHJ4YrrusYNXzv1blewfER/mrKHXpqLYc/YOcpnOovJUX5nFLk7RpyHqHse4zeDNedIWnxJeE0QwBFtoUE9P3w7KbXwlqOqos7QA2shTuRFyyoyB/odsn+2MnlLn13Srf4kTI7K5K3kEFms/FEmbGVTA==
  template:
    metadata:
      name: mongodb-secrets
      namespace: databases
