apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
data:
  applications_api: argocd
  argocd.server_addr: argocd-server.argocd.svc:443
  argocd.insecure: "true"
  argocd.grpc_web: "true"
  log.level: info
  registries.conf: ""
  git.commit-message-template: |
    build: update image {{ .AppName }}

    {{ range .AppChanges -}}
    updates image {{ .Image }} tag '{{ .OldTag }}' to '{{ .NewTag }}'
    {{ end -}}
