apiVersion: apps/v1
kind: Deployment
metadata:
  name: librechat-rag
  labels:
    app: librechat-rag
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: librechat-rag
  template:
    metadata:
      labels:
        app: librechat-rag
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - aloy
                - joel
                - ellie
      containers:
      - name: librechat-rag
        image: registry.librechat.ai/danny-avila/librechat-rag-api-dev-lite:latest
        ports:
        - name: http
          containerPort: 8000
          protocol: TCP
        env:
        - name: DB_HOST
          value: "pgvector.databases.svc.cluster.local"
        - name: RAG_PORT
          value: "8000"
        envFrom:
        - secretRef:
            name: librechat-rag-secrets
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
