apiVersion: v1
kind: Service
metadata:
  name: librechat-rag
  labels:
    app: librechat-rag
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  selector:
    app: librechat-rag
