kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowrr-exporter
  labels:
    app: prowrr-exporter
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll
    keel.sh/pollSchedule: "@hourly"
    keel.sh/match-tag: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prowrr-exporter
  template:
    metadata:
      labels:
        app: prowrr-exporter
    spec:
      containers:
        - name: prowrr-exporter
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          imagePullPolicy: IfNotPresent
          args:
            - prowlarr
          envFrom:
          - secretRef:
              name: prowrr-secrets
          ports:
            - name: prowrr-monit
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /
              port: 9707
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9707
            initialDelaySeconds: 10
            periodSeconds: 15
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 1000m
              memory: 1024Mi