apiVersion: apps/v1
kind: Deployment
metadata:
  name: libretranslate
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: libretranslate
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
        instrumentation.opentelemetry.io/otel-python-platform: "glibc"
        sidecar.opentelemetry.io/inject: "true"
      labels:
        app: libretranslate
    spec:
      securityContext:
        fsGroup: 1032
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - aloy
                - joel
                - ellie
      initContainers:
      - name: init-libretranslate
        image: libretranslate/libretranslate:v1.8.3
        securityContext:
          runAsUser: 0
        command:
          - /bin/sh
          - -c
          - |
            echo "Initializing environment..."
            mkdir -p /home/libretranslate/.local/share/argos-translate/packages
            mkdir -p /app/db
            chown -R 1032:1032 /home/libretranslate/.local /app/db
            echo "Initialization complete!"
        volumeMounts:
        - name: libre-translate-models
          mountPath: /home/libretranslate/.local/
        - name: libre-translate-db
          mountPath: /app/db/
      containers:
      - name: libretranslate
        image: libretranslate/libretranslate:latest
        securityContext:
          runAsUser: 1032
          runAsGroup: 1032
        resources:
          limits:
            memory: "8Gi"
            cpu: "8"
        ports:
        - containerPort: 5000
        env:
         - name: LT_DEBUG
           value: "True"
         - name: HOME
           value: "/home/libretranslate"
         - name: ARGOS_TRANSLATE_PACKAGES_DIR
           value: "/home/libretranslate/.local/share/argos-translate/packages"
        volumeMounts:
        - name: libre-translate-models
          mountPath: /home/libretranslate/.local/
        - name: libre-translate-db
          mountPath: /app/db/
      volumes:
      - name: libre-translate-models
        persistentVolumeClaim:
          claimName: libre-translate-models
      - name: libre-translate-db
        persistentVolumeClaim:
          claimName: libre-translate-db