---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: seafile-service-token
  namespace: tools
spec:
  encryptedData:
    infisicalToken: AgBBmJB7F2HI5gk23QF11zSaSQ8K3y8TPT9DAfQhE2iP69l3RIUhKkgxqtARb2rc9HG3g46DrxqZicXqZT6d80WZhHMhranOyZ9IiIGVTy0n0jSeebSH3BVYKkX9dOzCDoR1/RSH4De0vsZ9pP8VxuKPWmT3KNGd6bT/+7oG3fMqH37WxcMnr/cZopA7KcDXDCOpcqjqRwXLfWOWcpj29PU1mwXdDGxOOWUQA8MNm6UkBNV7R+iTeYNrrv+zZqFZh9mqsoKNBPjWr+Dq0P9jgUersLLEEuNvnB3yvrZ/Ivx3Ow0DZNsKbkiVqPjpkQQw5GZvR8LqmMhGIY2HR2VBKrZJiubI/WnYekcWvU8GufvoejH4aYJfb+/h9zJT3K8mZrUfFjXSuWGlyYhkp5mPQ2dZZVs1+ci6VFegMxBdkiZ4/yY9FGkePdWMHoS9erWFT8ZpSu9F+1585PS1o/c2WJ+J/zumyMG+09D7Rasd8bn7z4TeZVMyB2LvmqqSCRwSDywb3lsR8z22MMGfSPL2jsVu5qBgWyG78U29GsifV9a5EloRK/9FQqsS716ZQBPVJbYaAwDfIoLmlOoQYSZTewRFeenKKP0GOoOQqt69n+vlhfzN5nBISNXjLbuNPNsz8L6eeTab25NbiG6g3Rk2+qH42b5MHp1RUpugVfGSmTP/rnCo1A5Y4fSDoTfjuFKK8wUbGNvPFmkSA+Bxfun2843K7LfCCqFohnsOyyLhnTJsj0OmFr/cSvovZAqSOXs9xn7kCPt9fYzUunqxoav+YqiEszZnw2FG1LllYxwn3qAYQwUEIil/mBHcTVburRXrjLumvV9GDVuPVrE=
  template:
    metadata:
      name: seafile-service-token
      namespace: tools
    type: Opaque
