apiVersion: v1
kind: Service
metadata:
  name: searxng
  labels:
    app: searxng
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.67
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: searxng
