apiVersion: v1
kind: PersistentVolume
metadata:
  name: meilisearch-nardine-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - nardine
  hostPath:
    path: /k8s/meilisearch
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-nardine-pvc
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: meilisearch-nardine-pv
  resources:
    requests:
      storage: 10Gi
