---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: meilisearch-secrets
  namespace: databases
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgCeoN2p0laeeXHSv2rALhvcuUA6BsRdR6JwgoMyO/s41FRrkPuuuxL2uOXVednuJpInJeT6st/coIKFJiLswK66DAcieh7fT41cCQ9bpn0YATDMNbNu2VO3IU3h5VfLRmOVta/06Rwm5AFfW9ypwx/Gq/bYoyKqZ4G28byifdOtg3y9QS8Ca3Rcjy/052XAXQp+NQZZTobW4m295om7tGQm5Ztgbs98t7dLPm9Hi8Z/uMxly3iAONI/MsnzWYmVh4qxI5+zNwKKhZ3GwyU98k2TOVbvAk1pzYrH0lMOQM+wlul8jchxYEylpx4ADablflfidD4EN8m3ilGE4iCoSQPgT0WlSHeW2DOfYY05wSgP1+SyVrvlYrXy+WM1pmAr7fRRGFPOnWkN6pYXKYegzau5Xiwg7Ngu7yc5VO2ShGxQwW9/HuQJDvClqSjUj8m0pY5WSYwu8e06yV7JbDXAFg8g3kCllDgXY6R4WN9rWEJ7fYg22vy2oPv6uuR4BpCNfQM4ak7yjorK3I/raD+a5NnZqliiELUy56XEo8+8k1ulEzQmx83cUdnf0Q2MZHfM/PvAzegKTGAAc7Id0Qo7M2cTCH5NRSMmXyyWlfZ6NT+Qe7TOe3ZV/BVDyIHQ/iVRxNJlg3ULF4UtISMPN+EAKMboFo7zxLr9bmoPT7lYtLcAyVET2PnDZDL7UhmufMp0OUq36SIrpesrrL86rLR1MOfQFELuiERQxhFIMfUM9MgFGQ==
  template:
    metadata:
      name: meilisearch-secrets
      namespace: databases
