apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  labels:
    app: meilisearch
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 7700
    targetPort: http
    protocol: TCP
  selector:
    app: meilisearch
