apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signoz

helmCharts:
  - name: k8s-infra
    repo: https://charts.signoz.io
    version: 0.15.0
    releaseName: k8s-infra
    namespace: signoz
    valuesFile: values-k8s-infra.yaml