---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unmanic-movies
spec:
  storageClassName: longhorn-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi