apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: k8-operator
    app.kubernetes.io/instance: secrets-operator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: secrets-operator
    app.kubernetes.io/part-of: k8-operator
    app.kubernetes.io/version: v0.9.3
    control-plane: controller-manager
  name: secrets-operato-controller-manager-metrics-service
  namespace: infisical-operator
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/instance: secrets-operator
    app.kubernetes.io/name: secrets-operator
    control-plane: controller-manager
  type: ClusterIP
