---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tracearr-service-token
  namespace: arr
spec:
  encryptedData:
    infisicalToken: AgCMVSVIkFpogFpx8VGdp7CsjQqq3NxqUATyck3l6+6EN2BYVFd74JJeMJbRn1UZPdLQvSXQULh7BGVOK+YD0ekoenF8sE+UXLTpAGBNsNm/JE5ZQQA9gkBIelmzPklEqpChWAkoFJuahS2pPK0UFNIJ+gJfU8PCKXHe1uku5BSoL71PF1RBb/I2JhfSfliRo2w061vkRl9TPcZyMd33+Mepwcr/xuUTyz/g97HmCURW+KH/1KsAtsAduHJtebF7LzK6ccWauuFrznpyobO1cJa3C0geZNJugmMO9I/8cb6/T10va4ycmx0pnk4EWVrv3POU3b6YCce1Vy3ASNCOBCAQPGrfruykHjlzeAKrXk1tX2dYeiENeFKK0KYkB84qcHXMv4XVy+p7cFhKcff/oBtQDtGHM54USmTCzugOUTpTl+gUyg30P5xUtA7CE7IGmVxTdRNWa683ZHW8QuEw+831ZqpfJ1oFVHlopFfkOxHOiQ6iC8dNCm4fpBhxzyf+xuUmk8cFAG4y/FhS+2kfLZfHuZxI0IBeqRVyBO9krN2JcHDLvxjrioSyQD3GSAhTcU/OAfV16+yUB8477K0naraG22qwKcqHDwm54pJDYMjBNQahYAFiMyobC1/zU2cekdAuUbHSZyVRHPXEwhhF/xYd/SmsWqmFrIJIuA+1FNFjK5uiOwAZzwO9Khzcr9c362ZYYldBjOugfcpk995yZ+K8i/BZ3uu9Vt0wy1VUaVzeTtqzE0BKJFm/zuF0SrITlW3ac1G7HqOLGr+TeQH1M/fGYl2YIGiZGkLJ+b5iWP6S+wVce1mLOTMlBXON12r45TXmJjLyOzt3bN0=
  template:
    metadata:
      name: tracearr-service-token
      namespace: arr
    type: Opaque
