apiVersion: v1
kind: ConfigMap
metadata:
  name: librechat-config
data:
  librechat.yaml: |
    version: 1.2.1
    cache: true
    webSearch:
      searchProvider: searxng
      searxngInstanceUrl: "http://searxng.tools.svc:80"
      safeSearch: 0
    mcpSettings:
      allowedDomains:
        - "*.vinicima.com"
        - "192.168.253.*"
        - "*.svc.cluster.local"
    endpoints:
      openAI:
        disabled: true
      agents:
        recursionLimit: 50
        maxRecursionLimit: 100
      custom:
        - name: "Deepseek"
          apiKey: "${OPENAI_API_KEY}"
          baseURL: "https://api.deepseek.com/v1"
          models:
            default:
              - "deepseek-chat"
              - "deepseek-reasoner"
            fetch: false
          titleConvo: true
          titleModel: "deepseek-chat"
          summarize: false
          maxContextTokens: 128000
          streamRate: 25
          dropParams:
            - "stop"
          modelDisplayLabel: "Deepseek"
      azureOpenAI:
        titleModel: "gpt-4.1-mini"
        groups:
          - group: "hackathon-arbi"
            apiKey: "${AZURE_API_KEY}"
            instanceName: "aoai-hackathon-arbi"
            version: "2024-06-01"
            models:
              gpt-4.1-mini:
                deploymentName: "gpt-4.1-mini"
                maxContextTokens: 128000
