apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: linkwarden-infisical-secret
spec:
  resyncInterval: 60
  hostAPI: "https://cofre.vinicima.com/api"

  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: linkwarden-service-token
        secretNamespace: vault
      secretsScope:
        envSlug: production
        secretsPath: /linkwarden

  managedKubeSecretReferences:
    - secretName: linkwarden-secrets
      secretNamespace: vault
      secretType: Opaque
      template:
        includeAllSecrets: true



