apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keel
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  - pods/portforward
  - configmaps
  - secrets
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["apps", "extensions"]
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs: ["get", "list", "watch", "create", "update", "delete"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["get", "list", "watch", "create", "update", "delete"]
