apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - sealedsecret.yaml
  - deploy.yaml
  - infisical-sync.yaml
  - rbac-clusterrole.yaml
  - rbac-clusterrolebinding.yaml
  - serviceaccount.yaml
  - svc.yaml
  - ingressroute.yaml