apiVersion: v1
kind: Service
metadata:
  name: syslog-gateway
  labels:
    app: syslog-gateway
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.238
  type: LoadBalancer
  selector:
    app: syslog-gateway
  ports:
  - port: 514
    targetPort: 514
    protocol: TCP
    name: syslog-tcp
  - port: 514
    targetPort: 514
    protocol: UDP
    name: syslog-udp
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: metrics
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800