apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd-k8s.vinicima.com`) || Host(`argocd.vinicima.com`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
          scheme: https
          serversTransport: argocd-transport
  tls:
    secretName: vinicima-com-tls