apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ingressroute.yaml
  - serverstransport.yaml
  - servicemonitors.yaml
  - image-updater/crd.yaml
  - image-updater/deploy.yaml
  - image-updater/rbac.yaml
  - image-updater/configmap.yaml
  - notifications-sealedsecret.yaml
  - notifications-infisical-sync.yaml
  - notifications-configmap.yaml