---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-proxmox-config
  namespace: mcp-proxmox
spec:
  encryptedData:
    config.yaml: AgAha+l9j/51MnKt/9Qc2FT1pUnJEN9sAi/Z+or5r3u26TIM8tLMXylZsYU5GvINKwoUSAQYmJQnZsD2B8A8+BZ+a93ay9gBwMc8wzX8PMRtU721G2l7mDJv9rMEofLuS4aKQ8jyfbxYvLgcXpOvRtcCOygeaIs3mUQpDVgakRccs85vrxaLrr4K1AXZFxNqCRunai9+rI2DTnsGnIAZvGSgUDFD/BjNeUFIeTC4p1d3SiFlZI9oEgM1cDYdctxy4H5jrq6AlE8Kug2/KDwcPylEo3J/UVWSVkChiVyudyfbSc9fRY4d9UxkRznx4RR2KeeQI549lWb7EuTqqFgsdpqHkTc5oNrBbN3PiooHyliAqcyhNtodFyGjwYWTz//JW81QukTK4CyhhLfp++HopjX1NamkIWysKXRpnozxEZZnuEeZ00A4XUsvvSeOy4kivfIkV9DyUrRhsK4YiUgEcIH0s0ze2CkWnAL0z8k/9Xp7sxVnmN81acYClMpDblYnEHCPXGhwfHrBA9kYKcWhVtePBRMcyH6ypZvP3gYyTk7KwzXRWr8InizP7XIY/BRS0LxWVhbOm0X1ssKFeOkpQVsT5QoQhMIT/rJecTjwAVbtqc9bt0/aqX8RwMThPg0yKYWVCfp3MfYssm7l8IPf1/f9+7uEe5Yn1MJtKedEyjb2Uo6n05fUeyZhwIaoIxAJyLXY8IS2exTyMazp/Cmumonjb6yKZxIH/l+JD/oL1VpiYOZ+PhqyE2Ewg4HAaBBNimcaaYwpqIfBIgcfQGKBxNW39Z2rAn1NelpvWYpuohXek2+7seG2C0fN8wRkfIcavsSqDaK3xaOmATi7S48mhYiLLyg40Kg4v37IcoTHF399HdgchZ6cmAtCz6jf3hv/bfWouejKS35B80bJnE9ScfOtImD9hnuT2GnZyQao38Qyl/yKIJ0WNkbMcCk6aGXg0DrRsHA3AF3ct3bLyBedp0s9St0vQ26cTiPSkFERT9KTuSiF7fW/hEO9fq8vRIRJgk3YFZoGo2/5Z+YNNmtr2e5m0QgszjI=
  template:
    metadata:
      name: mcp-proxmox-config
      namespace: mcp-proxmox
