apiVersion: v1
kind: Service
metadata:
  name: mcp-proxmox
  namespace: mcp-proxmox
  labels:
    app: mcp-proxmox
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.253.43
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: mcp-proxmox
