---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-photosync-dsoares
spec:
  storageClassName: longhorn-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi