apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: infisical-operator
    server: https://kubernetes.default.svc
  project: vinicima-prod
  source:
    path: kustomize/infisical-stack/infisical-operator
    repoURL: git@github.com:vinicimatecnologia/k3s-homelab.git
    targetRevision: main
  syncPolicy:
    automated: {}

