apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: vinicima-prod
  source:
    path: kustomize/metallb-stack/metallb
    repoURL: git@github.com:vinicimatecnologia/k3s-homelab.git
    targetRevision: main
  syncPolicy:
    automated: {}

