apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: vinicima-prod
  source:
    helm:
      parameters:
      - name: fullnameOverride
        value: reflector
    path: kustomize/cert-manager-stack/reflector/charts/reflector
    repoURL: git@github.com:vinicimatecnologia/k3s-homelab.git
    targetRevision: main
  syncPolicy:
    automated: {}