apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: vinicima-prod
  source:
    path: kustomize/vault-stack/vaultwarden
    repoURL: git@github.com:vinicimatecnologia/k3s-homelab.git
    targetRevision: main
  syncPolicy:
    automated: {}


