apiVersion: v1
kind: ConfigMap
metadata:
  name: freshrss-constants
  namespace: tools
data:
  constants.local.php: |
    <?php
    define('FRESHRSS_USERAGENT', 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36');