---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: freshrss-service-token
  namespace: tools
spec:
  encryptedData:
    infisicalToken: AgCv6eR8BWQrWr6B+CqTsnpQ1y88dNI4CTVwFVr5iGVfB4eWUy8AytLlVdIa157jDoxgdJC9TsqjwUL92fS0xyvN6DjmlQeqvELUYCoJe/QjeG3FxRBWdrJV72T00NW/fvsaWc21H0o1Z+/JSn2zSqJtp5zsP7bWp/kWuCPNzyDFkylRKwu9fiG+7ObydEcLRqJlSkWgJ41cgih23AsqOpIGbOk8U8bU+GB4hgzg0IvbcfKIZQVu1gWGOtigzcDhhLO9hS3XLfvyQdPCnjDUvktxnk4/LfU3RaQKBWzx/oaGvgoDZNy9dVDSlEtKirOvrn+UfZuc3wO7i9sPLSKqRLMCiFmoVRWiKW3R5wYwiXo36yGqdtk636bK0gQvuFmbKhpa1ye9YQuPY5hlj4IJuiAteIoa11McisMiEbZ3qLNFlnm6DREGyh3VN+W5uhhdbiEtexjBzBNZsk0hfvEK04m0q46LRIJ4YLC57giOxaspedGFiQCFAAeVBaSjArJE1Q4KBoxz1JfserAnwVzF0f8gI7GTjYuOdWYmzvOuVdlGEUt8+J86R6szxRC5vFBkeSgLz40ovCxpNYp9N9/advvHgn+wJFoSgn82Eh1I03/z9PZBom/PDFyyPo9a+KfLj5dczXACIUtHiTpt6fSgzJmFwmUFinZ78UU+SYEhTm+r94+NzHtVSVwKs4SwjlYMF5P7gIl6FLt0lzXlDXMO3I8T3KL3uqa/cWi9BH6gTBt/VKC86ToLwn7HFoDm6NowzH3bHxg+8Hw0AYOAPgZg5xBDToE3T2cbKkVSo2bEhq2jqyt34Nh8GiTpXuqra1phid6ulBIusx4ctTQ=
  template:
    metadata:
      name: freshrss-service-token
      namespace: tools
    type: Opaque
