---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-service-token
  namespace: traefik
spec:
  encryptedData:
    infisicalToken: AgDKM/kcNyPi4i6pFRxpJCZgEB1yjNco8J5d9h+moLdiJND6XjuCyfEUNBdjRYutKqU+K8gsHwgNEPSuFJbnxKseY5peYXH6kG2pZZiIX3goNw+8t+R5jVp3WcYhIrY0D8/JPZtKIL9MWgivnhFK7ppYn3YWVq7DfGbGZ1s2Z08yXn54mVj+D5ee/Qtc/xYnS9QS33lTpDN4umDFdYGgbZRYAWhmTH74P2UoMHPAVoTV22RGwMbzwUy2QIiyn/ZdrpPb8YOHxlYnjoAZTMqcR31uMPxlIdOAgAqXZa0XutVLEUepgoZXVEdqJnA0PgbQdfT6uqWxOlxC3bbuV/bcvXB/LriM01sG6Cy+zBh6/Y7L06ruPhD4wNPhMxI3Q1pQ3u86Wi2MV0B5aCwgBBlBpc0N5Qo6HOFguFS/ZJvNQZCCpxDu6toOUQZAoTkmceYpK5HdxqXV/MaeZbjUlKBupsX/WAwqa4LFt6EBCfxis9zIb9UXomA60TE5UedPiM1qmo6joBe9BrAK+L0wTCkB1BwvlONhS00yZrGuDcvFpVIsCnqc+bdxC4TcH9DXPr3KbX1QDNIkhoQ5f8iXBx1mB2rAICD98DrhlL21lHHw/fn648cZwTsfKVee99AtFh0madI0vAzHGvO9ZiWZg4uQy4oSEB/ELByh2IBm7W2vcNQk5kxcNOLR/Pd2ZaOlLf76cl2K688Njd2IYWbgUl9YPVNVmQ+VhNDOcbebSTr290edjwVwkQD2OHw3bbU/z8Y8wr9d0nNRSmIv+wDLePq2CbsjX8XJn9F2oXVssZpSBajY0vf+5na9Sa3Y5b3faTe5OWCE1n/NMuWgWG8=
  template:
    metadata:
      name: traefik-service-token
      namespace: traefik
    type: Opaque
