apiVersion: apps/v1
kind: Deployment
metadata:
  name: neutarr
  labels:
    app.kubernetes.io/name: neutarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: neutarr
  template:
    metadata:
      labels:
        app.kubernetes.io/name: neutarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - ellie
                      - joel
                      - aloy
      containers:
        - name: neutarr
          image: iampuid0/neutarr:latest
          ports:
            - name: http
              containerPort: 9705
              protocol: TCP
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Sao_Paulo"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: neutarr-config