apiVersion: v1
kind: Service
metadata:
  name: neutarr
  labels:
    app.kubernetes.io/name: neutarr
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.22
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: neutarr
  ports:
    - name: http
      port: 9705
      targetPort: http
      protocol: TCP