---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lingarr-animes
spec:
  storageClassName: longhorn-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi