apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lingarr-animes
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`animes-lingarr-k8s.vinicima.com`) || Host(`animes-lingarr.vinicima.com`)
      kind: Rule
      services:
        - name: lingarr-animes
          port: 9876
      middlewares:
        - name: body-size-50m
          namespace: traefik
  tls:
    secretName: vinicima-com-tls