kind: Deployment
apiVersion: apps/v1
metadata:
  name: ryot
  labels:
    app: ryot
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: ryot
  template:
    metadata:
      labels:
        app: ryot
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - nardine
      containers:
      - name: ryot
        image: ghcr.io/ignisda/ryot:latest
        ports:
        - name: ryot
          containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 15
        envFrom:
        - secretRef:
            name: ryot-secrets
        volumeMounts:
        - name: ryot
          mountPath: /data
      volumes:
      - name: ryot
        hostPath:
          path: /k8s/ryot
          type: DirectoryOrCreate
