---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ryot-service-token
  namespace: arr
spec:
  encryptedData:
    infisicalToken: AgB+NEbfPP07GcMpHlv4MtWY+jmFcMc7oTtfI9Lf0cfa+40unEChhuS/QLs3cneoVcaB26jI+ShYJeXSlOW7eDpWjww+BqfM1ZpjC1pKJ/2BpQfgdn6B5BUaaWtfw8GVoiIFyOAlX6y4cZfbcgiXwoe9SAR6RpaX6oeqvaWCsuoA4BBgEu1j6pcKHVbwU1CIrV1ElwAuwnipGgtXp8rdOlhdvld4YQJ3aotSnluSQq9oycNZmduY6rIM0YcEdmnQGz65cLD43iu7YZC45VTOLHtnmQ5e0o7v3FZfi3VEHiV8XkYM3eU10+SW0fClCGso1PH6yRd5oU6s08AvKfwNunCICy+Eu9O/LceiU30iEeFEh62OKRg67nhqpHIMKffHwwf/3ZGsnh9IWbsUwu8QwNftWF0b/WmgZGMIXa3SCCFz1NO+Z6bO5Dc0ZkvzmmA5iIUPQrRCHGaqHZny7YmojpBirUHwHC8UpGYmMCbBZ/5JYTfbKp5b3p8zaPZaoWUJlFRKgz1dYxokSOTrITyR9oA2RTn93BX+K2XOkDnkd+FeeCExrnCsG1JHSHufHw92pMMIWvyyDcrm1kRkbHZTXgSqqrXP9e8M5ObcXlxO2HAwqX++B1sZdDFIv5DydCJIsQxXpCaPbbeOxiPSO2yc1FzhWfMZ8UoyL3htPFp0C3+fddlEnddHTy+xH0LaUNoVR1IXfYRrVK3XXzHx6xIpb9hOblxT2u5NALNNAmJDHrCcp3KidH/Y7FEc7Ev/b/JO3u7SJSQ6H5xHPdQzQX/kIh1WfOWdlfv51WJra1cg7k/EKj+7J/aUQSghxf+4ku2+v6N6rHIjS0lJfF4=
  template:
    metadata:
      name: ryot-service-token
      namespace: arr
    type: Opaque
