apiVersion: v1
kind: Service
metadata:
  name: ryot
spec:
  externalTrafficPolicy: Local
  loadBalancerIP: 192.168.253.40
  selector:
    app: ryot
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: ryot
