---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: autobrr-proxy-service-token
  namespace: arr
spec:
  encryptedData:
    infisicalToken: AgBWMICLDSL1PJOdcv3Gnr5Xj9OuucFz7GQi0dft3Jpshk0fl4GWjwcE5EvoRd+N8ln/Hpkzn4muWZ7XR2Ts0b1KRhfMRqyXH1FFevapVKRKcPoEO/t4w+hIk+rqAXcyMu2hTNo/yPaMjMPRNQN7nsvHtdzbSRaMYU3zgGT59ixhaqvWrojt8pmrY5UTyXYJgJiBDscFejciyCR5ziSk9ey8lhMvbngii+BGlMuWegoH2Z8WDdTdQpsJHkOJYR5qSIW+5MpvIgPpaQm4GYU6/C41dW8377NZmqzGRjQoRJC59K8cNBVxz8P43Qr7nFZC6JT9DDFOuiJVLle2ng0TQDsAK/dlYktIzVGfvj0tgh1Tb9BU2wMV1PsHbmE6sxi5ImRldq8snJsjYvFyW7vqpqHvBPPwHQPwE1ASGM8s+JReYvtzq3nhcUqGIaJjVF8u7ptRy/IYhRwOcwcWKkBuC1cUrlFdcZ6D5Ar7ir2UDDoTQLwJgoZkfxBojaMrOx0Ofqz7NW3pmW/drOxsjYHgbUQ9owtarSVrg03bDM5HdAHtiqEG1m2cKB30O5f1WkGeJHgE44FjzjMclp1HgRM3q6T1WQKNHcSw0M7z8KzdwdhlMUZJxJA3JOtz526kfFRlqyU5U/zGlGbk0UzY4rIBuXC5gXBCTY34lkHPOhG3Bp7Fi3NXbIQDZCJ6LOH+jd9bhusn7sMJSIq3wlR73Eh5dJMdVDAx9slMNQ9+PgPwyykMYvv1ZlMkgPw0pazmWmoUlVYbOVsBQ3aOozvFZg2LYeDyllOZ9G1JcrVwZjaAClRWIkEnpRKmgZYDWzjF0BV4mkLQAZrMCYgt58E=
  template:
    metadata:
      name: autobrr-proxy-service-token
      namespace: arr
    type: Opaque
