apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

resources:
  - ns.yaml
  - sa.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml
  - sc.yaml