---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-signoz-secret
  namespace: mcp-signoz
spec:
  encryptedData:
    SIGNOZ_API_KEY: AgB3x4tFkSUIIgIB2z3+ikQoJCLysCnuRnlRo5ckO40GmkL+WUK/tNynr22pqT8ttLAdlIPPN06IVQQgapzAOxZcwsZsj1gWCUNfd8gajkO0JI6Gwp3cT+XUXq7FmQAVpMYva/mViCXU2aYzHuikXAkmdjwdZBnIvsxU3CG5Y3DUdi5K3iJN1dp1A5bQapW6jmBFnK18rbujtBOLomX9H7XI4rdOXu5DWMfPHuKtZki/tAzHsgZ3o/5PocH2fcIe1AkUSqVnGMtxVywEE84ulzmGAXFbrKqgxDnJVhkJmTx6nT0jbJwKTyI8UGd/IpUdthjCDpEvq+h+U3o+skC+7yK5KIW+XoiFXe6N9uV0I0rLO1Jd8ysDwdYhMYvrI8bRX+I3StXQQbAypvRSfa+qg+aelwkd1Nr8FXqS7X5HW1d4on40EoriO5Lk6rCxGJsvMj4Y/pgpMw5SJvPDNR/vTAwm6XX2G1L7+ZbHtH75TWZjlDR6/tzGyaa1bBcch+Vj/ESL3XVeoo0VHbsll58kk/bD9WSrlhoARDH09hGmZHMdpkT42HIOErZByGV/09CX4fW7KAFUZPBOSXH2C3C2ivYv87LuTuRAn2CZs2UbJPBjlfWj/UGrSX4lg5O/YxI1XEywKprVIC2eHYe6q3KM+meNMwbUmxHfL/hwBzi4to/mFXMnSRYHpCMOINCbYy7kOxPcNaMtzTQ7f1jbwscxeffKrW4aQ1AS+8TIUvjXnNKgd8a5B8KpQx6eK/Ph8A==
  template:
    metadata:
      name: mcp-signoz-secret
      namespace: mcp-signoz
