apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - serviceaccount.yaml
  - role.yaml
  - clusterrolebinding.yaml
  - clusterrole.yaml
  - deploy.yaml