kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr
  labels:
    app: prowlarr
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-dotnet: "true"
        sidecar.opentelemetry.io/inject: "true"
      labels:
        app: prowlarr
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - nardine
      containers:
      - name: prowlarr
        image: ghcr.io/hotio/prowlarr:latest
        ports:
        - name: prowlarr
          containerPort: 9696
        envFrom:
        - secretRef:
            name: prowlarr-secrets
        volumeMounts:
        - name: prowlarr
          mountPath: /config
        - name: p2p
          mountPath: /data/torrent/complete/prowlarr
        - name: usenet
          mountPath: /data/usenet/complete/prowlarr
        - name: custom-definitions
          mountPath: /config/Definitions/Custom
      #  - name: betarr-script
      #    mountPath: /etc/cont-init.d/99-betarr-setup.sh
      #    subPath: install-dependencies.sh
        livenessProbe:
          httpGet:
            path: /
            port: 9696
          initialDelaySeconds: 30
          periodSeconds: 30
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 9696
          initialDelaySeconds: 10
          periodSeconds: 15
      volumes:
      - name: prowlarr
        hostPath:
          path: /k8s/prowlarr
          type: Directory
      - name: p2p
        hostPath:
          path: /data/torrent/complete/prowlarr
          type: Directory
      - name: usenet
        hostPath:
          path: /data/usenet/complete/prowlarr
          type: Directory
      - name: custom-definitions
        configMap:
          name: prowlarr-custom-definitions
    #  - name: betarr-script
    #    configMap:
    #      name: betarr
    #      defaultMode: 0755