---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: autobrr-service-token
  namespace: arr
spec:
  encryptedData:
    infisicalToken: AgBEdSOAECV1rP9Kgu/qjoYSGPf2GyW27dNj1BolMlAuIMxlDdzyTdygaix9upMd3gJ/HVx+RXQp2CeRJNyZMS+examQJJe83wqlgdBk+xSsBgcpw1B7f5rYDPOYVBCWOlX4zRA4ndoDKjGbSQEGWK/PEKDUYvqqNQjHYM5U0YO4KdNqreQraIjw3RJGU/yarCGOIAc2Tw2xbFCMkh4X/k8zoMTd7yzKfIMozCpGFccq3rWptUo2FXYcKubMV2WEubKfAPQoVsyXAR7Lbkc77rcjZhmCuAN0r7LWeMzuEpUMsBK1nX2I1u7h5+qPkkQlIlQ8yKtIvhiRfKd8qilhk0EGEIleIKpWm9frgmymKS8xKUNYqm3/Qexz+kh3qhQ5Ii47xCIpvhKlv1gptS9gnTWeksVNsD7NEHCPmyO2FwY92+mYHYquCzwIVtqb+3ar/7Bmj8TGUumrPQ0z7bGVz/ZPhZOmWyvw5DEl8j74FAltRTbUgCT/jyK4VezIu+/8yvKjECOTbrMTUiTDG1E/IMsBHggfP48XSdvk1uPKnHGIJpFhGefvjV1ps7CHMrX1cQfB6mQGv22w5LXuFuFMmB9jvX3aA+fz9NVQseR6G84PsUOq6RNpk3H4QRhzQxfn75aRzImUQvnEFE1y03/FmqXE6DtTiOivLRE+avzBcIbGQ3G4h3i8RS6tyHABYdZY5xgk8KZmZM8K2tAF1z1rW28DH6rosr1e478MbCoi+Tx2ku21LuXmsHsJMzn9KykMgvxO7XIRq7/6b1CjX7LOlJ/M6m2vBQNyTKyLUZGWAjA0sqvbynyeXjnsfVuHDFsK4CN6k52lx28nPjk=
  template:
    metadata:
      name: autobrr-service-token
      namespace: arr
    type: Opaque
