---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: romm-service-token
  namespace: arr
spec:
  encryptedData:
    infisicalToken: AgCY1RPczFZMGyMiqS+ADG3r6JBjc6F2PU/LDptL1rbREpRqAY2Y6cPb6HxMcKertdHVimMu9LeyXGR57Y2VsCtrMXjB0+MBYica5TxvfAdA2JPrreikExQX77CnC1z8SMFck0rAzDL5z+ktPYLL9aEBosMb/z/Gurbt6aDJ0CpWi1eonznfTgu408pgNHOl2I1MDaWIKpT12YJRGDSp26BtGl31iVcB58lczx83jVAyBOEF3XC+sjrysRlmeFTejlKzmSTOeT8Lxc4epNLanOfPi1VP4kN0k9CemYbPcZGXHzDG5L8Z0PP1vH+E8wkcqIBWEAIKjxifu8K27J5DjlxgWAJmwJbmHNMS+1dcvwlkn0vrVvJnlBlUItypU2Zqm22qL4JoYbT/w21unN4K6NzWM8IhcqsHA9F2PgGqu/Ewr4kV+f9V1V99RV9/r3OGID8oIl6CaiA9ZkdoRKp163mWP2Z5uZUBktgt5MxboZmy+nLKbuDaYrm7/M7pax5IDO/8rnwXEn0UWMzZDrD+jJAj1gUw23jDdonhnNYlm7juvkvhxiiAbsYbPLvNmzqGMKcFsUgZFtdULa2mz0vEwmdVukBs1Vgc8SD2W2jU1FUNoVbqmtdXAcJwLKDMJg7qy+3XjvHHPAmxrEMZ9CWcNb9fZI13mjZoYIYrnbeWNIxMOXJQJIAz94q15/XIRWWdP5FQTR9wZ06uHIFqrBBY34524nGYzpx4c7/z892MQTZRgtyezK+CgdOboUnl7RgJz2WA2MXsytx9es24Cfwf82rEDZbhzAZKZZDuJGX/5Giw1iAGVjgayJNl5byQ5yPzSslqsz9pRxLrGYA=
  template:
    metadata:
      name: romm-service-token
      namespace: arr
    type: Opaque
