---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mcp-k8s-auth-tokens
  namespace: mcp-k8s
spec:
  encryptedData:
    tokens.yaml: AgBUYkLrPHe4HZoLAbbRBvxhvZopWtsu6/XZK0vE/ZFFJhENRm2Wcu2O92aEnitcmx+JkRhbWeI50SezrGvZFo8SX6MToypWlAj89K6vGTX+iaejH9VqY/80ynkRP2RRqDOxPtrz0YTKXGk5LUu/R+g1he97AnSXsb+oysHSQWzxi+7y4xH4t/3blmizHLGI8SBkV7Z9ap9DXeeDQXKrXLrq5kxRLVgiwwGyGITHGX7SWKqVNWecFsdAfXxo+r1fuWLeBw5ff8tVuP2yCtm6PCR0kI2S0IYclRlOIrdp58eMwjXsY4LTOlFioRU6VV8BlSXVGDfG94LhhvzRf9O0h1Mj8Ylio1Qp5JtKA+WrlImpfye9JJzAGulgxCIheqyh2a0kHOnDvCdP90s72Pabqrt0gfyeN06LEMZlvzX82JrNfkDhW7wvkDU8SWjX/5zHfCJmLuPL0o2ha+4nBatrWeEhYIoH1Lk/6ZpEf6bwiQNAc9TYCScioUVi+L3p9PcFyye4CG9f7hByhaC2uAEWuI3mtXJsi50VByuobeg/5/jJWWQkKWXO4ke+ffmtanTDXGHfD8JQ6QAJp44qVpzr5lcz7po1RQsyEI53DwHCtCLe6OAvBrwLhQZIA/S2lHHoVjRbMvG0mrZ3kKsGvCBGhIrESggbyv0ax5G6TZsgmuO8AKTVmhzHRWQmT9N2RiGMeS/s4knwl7+HTB4ySPLsto/CNatLlTFHCDy1Ml9ngMdNWQlDQkqAHYEYg0rOSfcV8Ka2oTTSB5By3UJ1pylkzAGqG375iRci+DStrQXKxGUgdiquuo9+5eaoY0PLnQVSZ9S6cFWjrXIl4gHc19yIgyV7u5ZQQfTYHHClm+iuw5NEpKNGynVDCiRXFSQ0YFiPrbeNOpj/OicSaxNr9Eu4X54yfRPASZyaR+IPEEwnQvasU6jc80uF2Q2r35t5fpYpQ4asjLB4SXOQsVOOqB0p64mz/B/mQGNBZ56mLWqJEi+dIPBAhbw7cIbCsZby5waTfx1F0kJ+UWMD41e3OKPrYi3aZAc9egRxyJCNrGjb2r+MABHMXfj0Ygqcizj5/1wei8yvT3Seu3eyH9sp0rkTIM7T1aY/naAD7OUKE/0a45gzhCSqNKAw8tZlRadfdHi+w4D3ZAVVtOACVyaRLiuPVPj6Pv05evMQsQHoIWdlmjiY43dUDQEbi94jnfos1TNcjxuHVCMqPddIkMesE3WJyNeHt4wejc5EmbDIAwrtfdy/PDu3yQogYSL186Ns/aDq+vqDKiql/DSG6kfWPzgwVUu3XFqwWoggq5cQbm5C2NY3hwlHSn+dZHambM+E8caWHNzx7s/E6W6rnYOTH22D3/d1yQ==
  template:
    metadata:
      name: mcp-k8s-auth-tokens
      namespace: mcp-k8s
